name: Massa

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Massa image
      run: docker build . --file Dockerfile --tag rykcod/massa:latest

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: rykcod/massa:1.8.1,rykcod/massa:latest
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      env:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: rykcod/massa
