name: Docker Hub description - TESTv5
on:
  push:
    branches: [main]
    paths:
      - README.md
      - .github/workflows/dockerhub-description.yml
jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: rykcod/massa
        env:
          DOCKERHUB_USERNAME: rykcod
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}